{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "qfeed-ai.fullname" . }}-pdb
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "qfeed-ai.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "qfeed-ai.selectorLabels" . | nindent 6 }}
{{- end }}