apiVersion: v1
kind: Service
metadata:
  name: {{ include "qfeed-ai.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "qfeed-ai.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "qfeed-ai.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}