#!/bin/bash
set -euo pipefail
trap 'echo "ERROR: 배포 실패 (line $LINENO)" >&2' ERR

# --- 설정 ---
AWS_REGION="ap-northeast-2"
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
COMPOSE_DIR="$(cd "$(dirname "$0")" && pwd)"
SSM_PREFIX="/qfeed/dev/be"
ENV_FILE="${COMPOSE_DIR}/.env"

# --- 인자 확인 ---
IMAGE_TAG="${1:?IMAGE_TAG가 필요합니다 (예: ./deploy.sh abc123)}"

# --- SSM에서 환경변수 조회 ---
get_ssm() {
  aws ssm get-parameter \
    --region "$AWS_REGION" \
    --name "${SSM_PREFIX}/$1" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text
}

echo "SSM 파라미터 조회 중..."

# Spring Datasource
SPRING_DATASOURCE_URL=$(get_ssm "SPRING_DATASOURCE_URL")
SPRING_DATASOURCE_USERNAME=$(get_ssm "SPRING_DATASOURCE_USERNAME")
SPRING_DATASOURCE_PASSWORD=$(get_ssm "SPRING_DATASOURCE_PASSWORD")
SPRING_DATASOURCE_DRIVER=$(get_ssm "SPRING_DATASOURCE_DRIVER")

# Redis
REDIS_HOST=$(get_ssm "REDIS_HOST")
REDIS_PORT=$(get_ssm "REDIS_PORT")
REDIS_PASSWORD=$(get_ssm "REDIS_PASSWORD")

# JWT
JWT_SECRET=$(get_ssm "JWT_SECRET")

# OAuth (Kakao)
KAKAO_CLIENT_ID=$(get_ssm "KAKAO_CLIENT_ID")
KAKAO_CLIENT_SECRET=$(get_ssm "KAKAO_CLIENT_SECRET")
KAKAO_REDIRECT_URI=$(get_ssm "KAKAO_REDIRECT_URI")
OAUTH2_FRONTEND_REDIRECT_URI=$(get_ssm "OAUTH2_FRONTEND_REDIRECT_URI")

# CORS
CORS_ALLOWED_ORIGIN=$(get_ssm "CORS_ALLOWED_ORIGIN")

# AI Service
AI_FEEDBACK_BASE_URL=$(get_ssm "AI_FEEDBACK_BASE_URL")
AI_STT_BASE_URL=$(get_ssm "AI_STT_BASE_URL")
INTERVIEW_SESSION_REAL_MAX_TURN=$(get_ssm "INTERVIEW_SESSION_REAL_MAX_TURN")

# AWS S3
AWS_S3_UPLOAD_BUCKET_NAME=$(get_ssm "AWS_S3_UPLOAD_BUCKET_NAME")
AWS_S3_TTS_BUCKET_NAME=$(get_ssm "AWS_S3_TTS_BUCKET_NAME")
AWS_S3_CDN_URL_PREFIX=$(get_ssm "AWS_S3_CDN_URL_PREFIX")

echo "SSM 파라미터 조회 완료 (19개)"

# --- .env 파일 생성 ---
cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy.sh — DO NOT EDIT
ECR_REGISTRY=${ECR_REGISTRY}
IMAGE_TAG=${IMAGE_TAG}
DEPLOY_ENV=dev

# Spring Profile
SPRING_PROFILES_ACTIVE=redis

# Spring Datasource
SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
SPRING_DATASOURCE_DRIVER=${SPRING_DATASOURCE_DRIVER}

# Redis
REDIS_HOST=${REDIS_HOST}
REDIS_PORT=${REDIS_PORT}
REDIS_PASSWORD=${REDIS_PASSWORD}

# JWT
JWT_SECRET=${JWT_SECRET}

# OAuth (Kakao)
KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI}
OAUTH2_FRONTEND_REDIRECT_URI=${OAUTH2_FRONTEND_REDIRECT_URI}

# CORS
CORS_ALLOWED_ORIGIN=${CORS_ALLOWED_ORIGIN}

# AI Service
AI_FEEDBACK_BASE_URL=${AI_FEEDBACK_BASE_URL}
AI_STT_BASE_URL=${AI_STT_BASE_URL}
INTERVIEW_SESSION_REAL_MAX_TURN=${INTERVIEW_SESSION_REAL_MAX_TURN}

# AWS S3
AWS_S3_UPLOAD_BUCKET_NAME=${AWS_S3_UPLOAD_BUCKET_NAME}
AWS_S3_TTS_BUCKET_NAME=${AWS_S3_TTS_BUCKET_NAME}
AWS_S3_CDN_URL_PREFIX=${AWS_S3_CDN_URL_PREFIX}

# AWS
AWS_REGION=${AWS_REGION}
EOF

chmod 600 "$ENV_FILE"
echo ".env 파일 생성 완료"

# --- ECR 로그인 ---
aws ecr get-login-password --region "$AWS_REGION" \
  | docker login --username AWS --password-stdin "$ECR_REGISTRY"

# --- EC2 Name 태그 조회 (Alloy instance 레이블용) ---
IMDS_TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" \
  -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
INSTANCE_ID=$(curl -s -H "X-aws-ec2-metadata-token: $IMDS_TOKEN" \
  http://169.254.169.254/latest/meta-data/instance-id)
EC2_NAME=$(aws ec2 describe-tags \
  --region "$AWS_REGION" \
  --filters "Name=resource-id,Values=${INSTANCE_ID}" \
            "Name=key,Values=Name" \
  --query "Tags[0].Value" --output text)
export EC2_NAME
echo "EC2 Name: ${EC2_NAME}"

# --- 배포 ---
docker compose -f "$COMPOSE_DIR/docker-compose.yml" pull
docker compose -f "$COMPOSE_DIR/docker-compose.yml" up -d

# --- Alloy 설정 반영 (bind-mount 변경은 up -d가 감지 못하므로 reload) ---
curl -sf -X POST http://localhost:12345/-/reload && echo "Alloy config reloaded" \
  || echo "WARN: Alloy reload 실패 (무시)" >&2

# --- 이전 이미지 정리 ---
docker images "${ECR_REGISTRY}/qfeed-ecr-backend" --format '{{.Tag}}' \
  | grep -v "^${IMAGE_TAG}$" \
  | xargs -I{} docker rmi "${ECR_REGISTRY}/qfeed-ecr-backend:{}" 2>/dev/null || true
docker image prune -f

# --- .env 파일 삭제 (보안) ---
rm -f "$ENV_FILE"

# --- 결과 확인 ---
echo "배포 완료: ${ECR_REGISTRY}/qfeed-ecr-backend:${IMAGE_TAG}"
docker compose -f "$COMPOSE_DIR/docker-compose.yml" ps

# --- 헬스체크 ---
echo "헬스체크 대기 중 (최대 120초)..."
for i in $(seq 1 12); do
  sleep 10
  if docker compose -f "$COMPOSE_DIR/docker-compose.yml" ps backend | grep -q "healthy"; then
    echo "✅ backend 컨테이너가 정상적으로 실행 중입니다."
    exit 0
  fi
  echo "  ... 대기 중 (${i}0초 경과)"
done
echo "❌ backend 컨테이너 실행 실패 (120초 타임아웃)" >&2
docker compose -f "$COMPOSE_DIR/docker-compose.yml" logs --tail 50
exit 1
