apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qfeed-backend-k8s-namespace

resources:
  - ../../../base/backend

images:
  - name: 092399857215.dkr.ecr.ap-northeast-2.amazonaws.com/qfeed-ecr-backend
    newTag: "9da7c33"
