apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alloy-extra-deployment
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alloy-extra-deployment
subjects:
  - kind: ServiceAccount
    name: alloy-deployment
    namespace: qfeed-monitoring-k8s-namespace
