apiVersion: v1
kind: Service
metadata:
  name: qfeed-backend-k8s
  namespace: {{ .Values.namespace }}
  labels:
    app: qfeed-backend-k8s
spec:
  type: {{ .Values.service.type }}
  selector:
    app: qfeed-backend-k8s
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}