#!/bin/bash
set -euo pipefail
trap 'echo "ERROR: 배포 실패 (line $LINENO)" >&2' ERR

# --- 설정 ---
AWS_REGION="ap-northeast-2"
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
COMPOSE_DIR="$(cd "$(dirname "$0")" && pwd)"
SSM_PREFIX="/qfeed/dev/ai"
ENV_FILE="${COMPOSE_DIR}/.env"

# --- 인자 확인 ---
IMAGE_TAG="${1:?IMAGE_TAG가 필요합니다 (예: ./deploy.sh abc123)}"

# --- SSM에서 환경변수 조회 ---
get_ssm() {
  aws ssm get-parameter \
    --region "$AWS_REGION" \
    --name "${SSM_PREFIX}/$1" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text
}

echo "SSM 파라미터 조회 중..."

GPU_STT_URL=$(get_ssm "gpu-stt-url")
GPU_LLM_URL=$(get_ssm "gpu-llm-url")
ELEVENLABS_BASE_URL=$(get_ssm "elevenlabs-base-url")

echo "SSM 파라미터 조회 완료 (2개)"

# --- .env 파일 생성 ---
cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy.sh — DO NOT EDIT
ECR_REGISTRY=${ECR_REGISTRY}
IMAGE_TAG=${IMAGE_TAG}

# Environment
ENVIRONMENT=dev
AWS_REGION=${AWS_REGION}
AWS_PARAMETER_STORE_PATH=${SSM_PREFIX}

# AI Service
GPU_STT_URL=${GPU_STT_URL}
GPU_LLM_URL=${GPU_LLM_URL}
ELEVENLABS_BASE_URL=${ELEVENLABS_BASE_URL}
EOF

chmod 600 "$ENV_FILE"
echo ".env 파일 생성 완료"

# --- EC2 Name 태그 조회 (Alloy instance 레이블용) ---
IMDS_TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" \
  -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
INSTANCE_ID=$(curl -s -H "X-aws-ec2-metadata-token: $IMDS_TOKEN" \
  http://169.254.169.254/latest/meta-data/instance-id)
EC2_NAME=$(aws ec2 describe-tags \
  --region "$AWS_REGION" \
  --filters "Name=resource-id,Values=${INSTANCE_ID}" \
            "Name=key,Values=Name" \
  --query "Tags[0].Value" --output text)
export EC2_NAME
echo "EC2 Name: ${EC2_NAME}"

# --- 기존 docker run 컨테이너 정리 (compose 전환 시 1회만) ---
docker stop qfeed-ai 2>/dev/null || true
docker rm qfeed-ai 2>/dev/null || true

# --- ECR 로그인 ---
aws ecr get-login-password --region "$AWS_REGION" \
  | docker login --username AWS --password-stdin "$ECR_REGISTRY"

# --- 배포 ---
docker compose -f "$COMPOSE_DIR/docker-compose.yml" pull
docker compose -f "$COMPOSE_DIR/docker-compose.yml" up -d

# --- Alloy 설정 반영 (bind-mount 변경은 up -d가 감지 못하므로 reload) ---
curl -sf -X POST http://localhost:12345/-/reload && echo "Alloy config reloaded" \
  || echo "WARN: Alloy reload 실패 (무시)" >&2

# --- 이전 이미지 정리 ---
docker images "${ECR_REGISTRY}/qfeed-ecr-ai" --format '{{.Tag}}' \
  | grep -v "^${IMAGE_TAG}$" \
  | xargs -I{} docker rmi "${ECR_REGISTRY}/qfeed-ecr-ai:{}" 2>/dev/null || true
docker image prune -f

# --- .env 파일 삭제 (보안) ---
rm -f "$ENV_FILE"

# --- 결과 확인 ---
echo "배포 완료: ${ECR_REGISTRY}/qfeed-ecr-ai:${IMAGE_TAG}"
docker compose -f "$COMPOSE_DIR/docker-compose.yml" ps

# --- 헬스체크 ---
echo "헬스체크 대기 중 (최대 120초)..."
for i in $(seq 1 12); do
  sleep 10
  if curl -sf http://localhost:8000/ai > /dev/null 2>&1; then
    echo "✅ AI(dev) 컨테이너가 정상적으로 실행 중입니다."
    exit 0
  fi
  echo "  ... 대기 중 (${i}0초 경과)"
done
echo "❌ AI(dev) 컨테이너 실행 실패 (120초 타임아웃)" >&2
docker compose -f "$COMPOSE_DIR/docker-compose.yml" logs ai --tail 50
exit 1
